from __future__ import annotations

import hashlib
import random
from dataclasses import dataclass

from .models import MemoryItem


@dataclass(frozen=True)
class CircularityWarning:
    memory_id: str
    warning_type: str
    detail: str


SYSTEM_TERMS = {
    "persistence gate",
    "persistencegate",
    "ordinary top-k",
    "risk_prevented",
    "stale_prevented",
    "utility_gain",
    "benchmark summary",
    "gate allowed",
    "gate blocked",
    "label_helpful",
    "label_risky",
    "label_stale",
}

LABEL_LEAKAGE_TERMS = {
    "risky candidate",
    "stale candidate",
    "helpful candidate",
    "treated as stale",
    "treated as risky",
    "label_risky",
    "label_stale",
    "label_helpful",
}


def stable_blind_id(case_name: str, memory_id: str, salt: str = "persistence-gate-audit-v1") -> str:
    digest = hashlib.sha256(f"{salt}|{case_name}|{memory_id}".encode("utf-8")).hexdigest()
    return digest[:12]


def detect_circularity(items: list[MemoryItem]) -> list[CircularityWarning]:
    """Flag evidence that may be contaminated by the benchmark itself.

    This is conservative: warnings do not prove bias. They identify rows that
    should be manually checked before being used as proof.
    """
    warnings: list[CircularityWarning] = []
    for item in items:
        text = item.text.lower()
        source = item.source.lower()
        kind = str(item.metadata.get("kind", "")).lower()

        if any(term in text for term in LABEL_LEAKAGE_TERMS):
            warnings.append(CircularityWarning(item.id, "label_leakage", "text contains benchmark label language"))
        if any(term in text for term in SYSTEM_TERMS):
            warnings.append(CircularityWarning(item.id, "system_self_reference", "text mentions Persistence Gate or benchmark terms"))
        if "external_benchmark" in source or "benchmark" in source or kind == "sample":
            warnings.append(CircularityWarning(item.id, "benchmark_generated", "item appears generated by a benchmark/sample rather than external evidence"))
    return warnings


def shuffle_for_blind_review(rows: list[dict], seed: int = 20260611) -> list[dict]:
    shuffled = list(rows)
    random.Random(seed).shuffle(shuffled)
    return shuffled
